#!/usr/bin/env python3
"""
Test script for Evaluator/QA Agent functionality
"""

import json
from agents import EvaluatorAgent

def test_evaluator():
    """Test Evaluator Agent with different quality reports"""

    evaluator = EvaluatorAgent()

    # Test Case 1: High-Quality Report
    high_quality_report = """# Research Report: Ultra-Processed Foods Evidence Analysis

**Target Audience:** Consumer
**Generated:** 2025-09-21 18:34
**Evidence Sources:** 15 unique sources across 8 domains

---

## Executive Summary

• **Research Scope**: Comprehensive analysis of recent evidence with systematic evaluation of quality and relevance
• **Potential Benefits**: Limited evidence for specific nutritional advantages in certain contexts [0,1]
• **Primary Concerns**: Multiple studies link ultra-processed foods to increased health risks including cardiovascular disease [2,3,4]
• **Evidence Conflicts**: 2 significant conflicts identified between different research approaches and methodologies
• **Consumer Guidance**: Evidence supports following established health organization recommendations with cautious approach

---

## Key Insights

Potential health benefits of ultra-processed foods are limited and controversial [0,1] ***MODERATE CONFIDENCE***

Multiple studies link ultra-processed foods to increased health risks including cardiovascular disease and metabolic disorders [2,3,4] ***HIGH CONFIDENCE***

Major health organizations recommend limiting ultra-processed food consumption [5,6] ***HIGH CONFIDENCE***

Research methodologies vary significantly across studies, affecting result comparability [7,8] ***MODERATE CONFIDENCE***

---

## Research Timeline & Evolution

**2024**
- 8 peer-reviewed studies, 3 health organization publications published
- Key development: Major systematic review published showing cardiovascular links [2]

**2025**
- 4 peer-reviewed studies published
- Key development: WHO updated guidelines on ultra-processed foods [5]

---

## Recommendations

**1. Follow Established Guidelines**: Adhere to current health organization recommendations while research evolves
**2. Balanced Approach**: Consider both benefits and risks when making dietary decisions
**3. Stay Informed**: Monitor updates from reputable health organizations as evidence develops
**4. Consult Professionals**: Given conflicting evidence, consult healthcare providers for personalized advice

**Risk Considerations:**
- Evidence is evolving and recommendations may change as new research emerges
- Individual circumstances may require different approaches than general recommendations
- Conflicting evidence indicates need for cautious interpretation of findings

---

## Limitations & Open Questions

**Conflicting Evidence**: Significant disagreements between studies limit certainty of conclusions
- Different methodologies lead to varying results across studies
- Population differences may explain some contradictory findings

**Open Questions & Research Needs:**
- Need more 2024-2025 research on ultra-processed foods
- Need comprehensive systematic review of recent evidence
- Need research on ultra-processed food effects across different age groups

**Methodological Limitations:**
- Search limited to publicly available sources
- Potential language and publication bias
- Time-constrained evidence collection may miss recent developments

---

## Evidence References

[0] **Nutritional Advantages Study 2024** Publisher: Nutrition Journal Date: 2024-03-15 Quality Score: 4/5
[1] **Food Processing Benefits** Publisher: Food Science Date: 2024-01-20 Quality Score: 3/5
[2] **Cardiovascular Risk Meta-Analysis** Publisher: PubMed Date: 2024-06-10 Quality Score: 5/5
[3] **Cancer Risk Study** Publisher: BMJ Date: 2024-02-28 Quality Score: 5/5
[4] **Metabolic Effects Research** Publisher: Nature Date: 2024-05-15 Quality Score: 5/5
[5] **WHO Guidelines 2025** Publisher: WHO Date: 2025-01-15 Quality Score: 5/5
[6] **FDA Recommendations** Publisher: FDA Date: 2024-11-10 Quality Score: 5/5
[7] **Methodology Review** Publisher: Research Methods Date: 2024-08-20 Quality Score: 4/5
[8] **Study Comparison** Publisher: Academic Review Date: 2024-07-05 Quality Score: 4/5

---

*Report generated by Deep Research Agent*
"""

    # Test Case 2: Poor-Quality Report
    poor_quality_report = """# Research Report

Some information about ultra-processed foods.

## Summary
Ultra-processed foods might be bad.

## Results
Studies show various things. Some say good, some say bad.

## What to do
Maybe avoid them or maybe not.
"""

    # Mock evidence list for context
    mock_evidence = [
        {"url": "https://example1.com", "date": "2024-03-15", "quality": 4},
        {"url": "https://example2.com", "date": "2024-06-10", "quality": 5},
        {"url": "https://example3.com", "date": "2023-01-20", "quality": 3},
        {"url": "https://example4.com", "date": "2025-01-15", "quality": 5},
        {"url": "https://example5.com", "date": "2024-11-10", "quality": 5},
    ]

    print("=== EVALUATOR AGENT TESTING ===\n")

    # Test high-quality report
    print("=== TEST 1: HIGH-QUALITY REPORT ===")
    result1 = evaluator.evaluate_report(high_quality_report, mock_evidence)
    print(json.dumps(result1, indent=2, ensure_ascii=False))
    print(f"Overall Score: {result1['overall_score']}/5.0")
    print(f"Summary: {result1['evaluation_summary']}")

    print("\n" + "="*60 + "\n")

    # Test poor-quality report
    print("=== TEST 2: POOR-QUALITY REPORT ===")
    result2 = evaluator.evaluate_report(poor_quality_report, mock_evidence)
    print(json.dumps(result2, indent=2, ensure_ascii=False))
    print(f"Overall Score: {result2['overall_score']}/5.0")
    print(f"Summary: {result2['evaluation_summary']}")

    print("\n" + "="*60 + "\n")

    # Test evaluation dimensions
    print("=== SCORING ANALYSIS ===")
    print("High-Quality Report Scores:")
    for dimension, score in result1['scores'].items():
        print(f"  {dimension.capitalize()}: {score}/5")

    print("\nPoor-Quality Report Scores:")
    for dimension, score in result2['scores'].items():
        print(f"  {dimension.capitalize()}: {score}/5")

    print("\n=== PRIORITY FIXES COMPARISON ===")
    print("High-Quality Report Fixes:")
    for i, fix in enumerate(result1['priority_fixes'], 1):
        print(f"  {i}. {fix}")

    print("\nPoor-Quality Report Fixes:")
    for i, fix in enumerate(result2['priority_fixes'], 1):
        print(f"  {i}. {fix}")

if __name__ == "__main__":
    test_evaluator()